export enum MaterialType {
  DEFAULT = "DEFAULT",
  METALLIC = "METALLIC",
  TOON = "TOON",
  PLASTIC_GLOSSY = "PLASTIC_GLOSSY",
  PLASTIC_MATTE = "PLASTIC_MATTE",
  PLASTIC_TRANSLUCENT = "PLASTIC_TRANSLUCENT",
}
